version: '3'
services:
  proxy-manager:
    build: .
    image: gott50/proxy-manager
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server
      - DEBUG=True
    env_file:
    - .env/.proxy-manager.env